/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { NEW_CHANGE_TEMPLATE_MESSAGES } from '../../../messages/index.js';

export function getNewChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-new-change',
    description: NEW_CHANGE_TEMPLATE_MESSAGES.skillDescription,
    instructions: NEW_CHANGE_TEMPLATE_MESSAGES.skillInstructions,
    license: 'MIT',
    compatibility: NEW_CHANGE_TEMPLATE_MESSAGES.skillCompatibility,
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxNewCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: New',
    description: NEW_CHANGE_TEMPLATE_MESSAGES.opsxDescription,
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: NEW_CHANGE_TEMPLATE_MESSAGES.opsxContent,
  };
}
