/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { ONBOARD_TEMPLATE_MESSAGES } from '../../../messages/index.js';

export function getOnboardSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-onboard',
    description: ONBOARD_TEMPLATE_MESSAGES.skillDescription,
    instructions: ONBOARD_TEMPLATE_MESSAGES.instructions,
    license: 'MIT',
    compatibility: ONBOARD_TEMPLATE_MESSAGES.skillCompatibility,
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxOnboardCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Onboard',
    description: ONBOARD_TEMPLATE_MESSAGES.opsxDescription,
    category: 'Workflow',
    tags: ['workflow', 'onboarding', 'tutorial', 'learning'],
    content: ONBOARD_TEMPLATE_MESSAGES.instructions,
  };
}
