/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { VERIFY_CHANGE_TEMPLATE_MESSAGES } from '../../../messages/index.js';

export function getVerifyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-verify-change',
    description: VERIFY_CHANGE_TEMPLATE_MESSAGES.skillDescription,
    instructions: VERIFY_CHANGE_TEMPLATE_MESSAGES.skillInstructions,
    license: 'MIT',
    compatibility: VERIFY_CHANGE_TEMPLATE_MESSAGES.skillCompatibility,
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxVerifyCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Verify',
    description: VERIFY_CHANGE_TEMPLATE_MESSAGES.opsxDescription,
    category: 'Workflow',
    tags: ['workflow', 'verify', 'experimental'],
    content: VERIFY_CHANGE_TEMPLATE_MESSAGES.opsxContent,
  };
}
